name: AutoTask
version: '1.0'
main: owleaf.AutoTasks
api-version: 1.20
author: NeonTheThinker
website: discord.gg/owleafstudio
commands:
  at:
    description: Ejecuta tareas automatizadas
    usage: /at <tarea>
    permission: op
  atreload:
    description: Recarga las tareas automatizadas
    usage: /atreload
    permission: op